function k(b,a,c,d,e){b.m.Cb(b.fb,a,c,d,e)}function l(b,a,c,d){b.m.ia?k(b,a,c,d):b.m.Ae()._OnMessageFromDOM({type:"event",component:b.fb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.m.D(b.fb,a,c)}function r(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Nb||(b.m.te(b.Rd),b.Nb=!0)}function aa(b){b.Nb&&(b.m.Le(b.Rd),b.Nb=!1)}window.Ha=class{constructor(b,a){this.m=b;this.fb=a;this.Nb=!1;this.Rd=()=>this.za()}bd(){}za(){}};
function ba(b){-1!==b.Va&&(self.clearTimeout(b.Va),b.Va=-1)}window.qe=class{constructor(b){this.Hc=b;this.Oe=5;this.Va=-1;this.Pb=-Infinity;this.Sd=()=>{this.Va=-1;this.Pb=Date.now();this.kb=!0;this.Hc();this.kb=!1};this.vd=this.kb=!1}j(){ba(this);this.Sd=this.Hc=null}};"use strict";
function ca(b,a){const c=a.elementId,d=b.fd(c,a);b.W.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{v(b,"elem-focused",c)});d.addEventListener("blur",()=>{v(b,"elem-blurred",c)});b.cb&&document.body.appendChild(d)}function w(b,a,c){n(b,a,d=>{const e=b.W.get(d.elementId);return c(e,d)})}function v(b,a,c,d){d||={};d.elementId=c;k(b,a,d)}
window.je=class extends self.Ha{constructor(b){super(b,"video");this.W=new Map;this.cb=!0;r(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=this.W.get(a);this.hd(c);this.cb&&c.parentElement.removeChild(c);this.W.delete(a)}],["set-visible",a=>{this.cb&&(this.W.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.cb){var c=this.W.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+"px";
a=a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{this.W.get(a.elementId);this.ld()}],["focus",a=>this.Cc(a)],["set-css-style",a=>{this.W.get(a.elementId).style[a.prop]=a.val}],["set-attribute",a=>{this.W.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.W.get(a.elementId).removeAttribute(a.name)}]]);w(this,"get-element",a=>a)}fd(){throw Error("required override");}hd(){}ld(){throw Error("required override");}Cc(b){var a=this.W.get(b.elementId);b.focus?
a.focus():a.blur()}};"use strict";const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let ea=0;function y(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ze?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.cf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;
function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let z=new Audio;const ja={"audio/webm; codecs=opus":!!z.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!z.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!z.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!z.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!z.canPlayType("audio/mp4"),"audio/mpeg":!!z.canPlayType("audio/mpeg")};z=null;
async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const D=[],F=new Map,G=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);
let qa=!1;
window.ka=class b{constructor(a){this.ia=a.ef;this.va=null;this.ba="";this.ec=a.bf;this.zb={};this.Oa=this.yb=null;this.Lb=[];this.G=this.Ta=null;this.Qc=!1;this.yd=0;this.mb=null;this.Sa=-1;this.Te=()=>this.He();this.Ra=[];this.A=a.Td;this.Ob="file"===location.protocol.substr(0,4);!this.ia||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.ia=!1);if("playable-ad"===this.A||"instant-games"===this.A)this.ia=!1;if("cordova"===this.A&&this.ia)if(x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ia=!1)}else this.ia=!1;this.Sb=this.oa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.De(c));this.D("runtime","create-job-worker",()=>this.Ee());"cordova"===this.A?document.addEventListener("deviceready",()=>this.od(a)):this.od(a)}j(){this.vc();
this.va&&(this.va=this.va.onmessage=null);this.yb&&(this.yb.terminate(),this.yb=null);this.Oa&&(this.Oa.j(),this.Oa=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}ne(){return da&&"cordova"===this.A}rc(){const a=navigator.userAgent;return da&&pa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}le(){return x}qc(){return x&&pa.has(this.A)}async od(a){"macos-wkwebview"===this.A&&this.Fc({type:"ready"});if("playable-ad"===this.A){this.oa=self.c3_base64files;
this.Sb={};await this.we();for(let d=0,e=a.Wa.length;d<e;++d){var c=a.Wa[d].toLowerCase();this.Sb.hasOwnProperty(c)?a.Wa[d]={Ze:!0,cf:this.Sb[c]}:this.oa.hasOwnProperty(c)&&(a.Wa[d]=URL.createObjectURL(this.oa[c]))}}a.af?this.ba=a.af:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.gf&&(this.zb=a.gf);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.Ge(d));this.mb=new self.oe(this);await ra(this.mb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ia?await this.Ce(a,c.port2):await this.Be(a,c.port2)}xc(a){a=this.zb.hasOwnProperty(a)?this.zb[a]:a.endsWith("/workermain.js")&&this.zb.hasOwnProperty("workermain.js")?
this.zb["workermain.js"]:"playable-ad"===this.A&&this.oa.hasOwnProperty(a.toLowerCase())?this.oa[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async lc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Ob)return a=await this.Ab(d.Ye?a:this.ec+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");
a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}ta(){return Math.max(window.innerWidth,1)}la(){return Math.max(window.innerHeight,1)}nd(a){var c=this.ba,d=location.href,e=this.ta(),f=this.la(),g=window.devicePixelRatio,h=b.$a(),m=a.nf,p=window.cr_previewImageBlobs||this.oa,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,A=window.lf||"";a=a.Td;var Z=(new URLSearchParams(self.location.search)).has("debug"),E=this.mb;return{runtimeBaseUrl:c,previewUrl:d,
windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:A,exportType:a,isDebug:Z,ife:!!self.mf,jobScheduler:{inputPort:E.Pc,outputPort:E.Wc,maxNumWorkers:E.Qe},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ec+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ec+"opus.wasm.wasm",isFileProtocol:this.Ob,isiOSCordova:this.ne(),isiOSWebView:this.rc(),
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Ce(a,c){var d=this.xc(a.ff);this.yb=await this.lc(d,this.ba,{type:"module",name:"Runtime",Ye:!0});this.G=document.createElement("canvas");this.G.style.display="none";d=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.ad||[],f=a.Wa;e=await Promise.all(e.map(g=>this.Ja(g)));f=await Promise.all(f.map(g=>this.Ja(g)));if("cordova"===
this.A)for(let g=0,h=a.jc.length;g<h;++g){const m=a.jc[g],p=m[0];if(p===a.Zc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ja(p)}this.yb.postMessage(Object.assign(this.nd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.jc,mainProjectScript:a.Zc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...sa(this.mb)]);this.Lb=D.map(g=>new g(this));this.md();self.c3_callFunction=(g,h)=>{var m=this.Ta;
return m.m.kd(m.fb,"js-invoke-function",{name:g,params:h},void 0,void 0)};"preview"===this.A&&(self.goToLastErrorScript=()=>this.Cb("runtime","go-to-last-error-script"))}async Be(a,c){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);window.c3canvas=this.G;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Lb=D.map(g=>new g(this));this.md();var d=a.Wa.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.ad)&&
d.unshift(...a.ad);d=await Promise.all(d.map(g=>this.Ja(g)));await Promise.all(d.map(g=>y(g)));d=self.C3_ProjectScriptsStatus;const e=a.Zc,f=a.jc;for(let [g,h]of f)if(h||=g,g===e)try{h=await this.Ja(h),await y(h),"preview"!==this.A||d[g]||this.qd(g,"main script did not run to completion")}catch(m){this.qd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ja(h),await y(h);"preview"===this.A&&"object"!==typeof self.hf.jf?(this.Gb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.nd(a),{isInWorker:!1,messagePort:c,canvas:this.G,runOnStartupFunctions:oa}),this.pd(),this.Oa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Oa,a))}qd(a,c){this.Gb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}pd(){this.Gb()}Gb(){const a=
window.We;a&&(a.parentElement.removeChild(a),window.We=null)}async Ee(){const a=await ta(this.mb);return{outputPort:a,transferables:[a]}}Ae(){if(this.ia)throw Error("not available in worker mode");return this.Oa}Cb(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}kd(a,c,d,e,f){const g=na++,h=new Promise((m,p)=>{G.set(g,{resolve:m,reject:p})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Fe(a);if("result"===c)this.Ie(a);else if("runtime-ready"===c)this.Je();else if("alert-error"===c)this.Gb(),alert(a.message);else if("creating-runtime"===c)this.pd();else throw Error(`unknown message '${c}'`);}Fe(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Fb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Fb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Fb(f,!1,""+h)}):this.Fb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Fb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ie(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}D(a,
c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ga(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}md(){for(const a of this.Lb)if("runtime"===a.fb){this.Ta=a;return}throw Error("cannot find runtime DOM handler");}Ge(a){this.Cb("debugger","message",a)}Je(){for(const a of this.Lb)a.bd()}static $a(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
qa)}static Hb(a){qa=!!a}te(a){this.Ra.push(a);this.Ec()}Le(a){a=this.Ra.indexOf(a);if(-1===a)throw Error("invalid callback");this.Ra.splice(a,1);this.Ra.length||this.vc()}Ec(){-1===this.Sa&&this.Ra.length&&(this.Sa=requestAnimationFrame(this.Te))}vc(){-1!==this.Sa&&(cancelAnimationFrame(this.Sa),this.Sa=-1)}He(){this.Sa=-1;for(const a of this.Ra)a();this.Ec()}aa(a){this.Ta.aa(a)}da(a){this.Ta.da(a)}Dc(){this.Ta.Dc()}Eb(a){this.Ta.Eb(a)}me(){return!!ja["audio/webm; codecs=opus"]}async Me(a){a=await this.kd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}re(a){this.Qc=!0;this.yd=a}ke(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}jd(a){return!this.ke(a)}async Ja(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Ob&&this.jd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Ab(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async De(a){const c=a.filename;switch(a.as){case "text":return await this.ie(c);
case "buffer":return await this.Ab(c);default:throw Error("unsupported type");}}ed(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ie(a){a=await this.ed(a);return await la(a)}wc(){if(B.length&&!(8<=C)){C++;var a=B.shift();this.xe(a.filename,a.df,a.Xe)}}Ab(a){return new Promise((c,d)=>{B.push({filename:a,df:e=>{C--;this.wc();c(e)},Xe:e=>{C--;this.wc();d(e)}});this.wc()})}async xe(a,
c,d){try{const e=await this.ed(a),f=await ma(e);c(f)}catch(e){d(e)}}Fc(a){if("windows-webview2"===this.A)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.A)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async we(){const a=[];for(const [c,d]of Object.entries(this.oa))a.push(this.ve(c,d));await Promise.all(a)}async ve(a,c){if("object"===typeof c)this.oa[a]=new Blob([c.str],{type:c.type}),this.Sb[a]=
c.str;else{let d=await this.ze(c);d||=this.ye(c);this.oa[a]=d}}async ze(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}ye(a){a=this.Ke(a);return this.ue(a.data,a.$e)}Ke(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=
a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{$e:a,data:d}}ue(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.ka;
function ua(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},xa={dispatchRuntimeEvent:!0};
function ya(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function za(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await za(b)}finally{URL.revokeObjectURL(b)}}
function Aa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ba(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await Aa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ca(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);function K(b){Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ga=!1;document.addEventListener("pause",()=>Ga=!0);document.addEventListener("resume",()=>Ga=!1);async function Ia(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ja(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ka(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ma(b){self.setTimeout(()=>{b.xd=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Na(b,!0)),document.addEventListener("resume",()=>Na(b,!1))):document.addEventListener("visibilitychange",()=>Na(b,document.hidden));return{isSuspended:!(!document.hidden&&!Ga)}}
function Oa(b){b.sd||(b.sd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function Pa(b){b.rd||(b.rd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Qa(b){await ya(b.url)}
function Ra(b,a){b.zd=a.message;-1===b.Lc&&(b.Lc=setTimeout(()=>{b.Lc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.zd)},250))}function L(b){if(!b.Z){var a=H.$a();a&&"any"!==b.Xc&&Sa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ta(),innerHeight:b.la()})}}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.$a(),innerWidth:b.ta(),innerHeight:b.la()})}
function Na(b,a){a?b.m.vc():b.m.Ec();k(b,"visibilitychange",{hidden:a})}function Ua(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=va.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Va(b,a,c,d){b.Z||ua(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Wa(b){window!==window.top&&window.focus();Ya(b.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){if(b.ub&&"pointermove"!==a){var d=b.ub;d.kb||(ba(d),d.Pb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.rb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:(c.movementX||0)+b.$b,movementY:(c.movementY||0)+b.ac,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,
twist:c.twist||0,timeStamp:c.timeStamp},I);b.$b=0;b.ac=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Va(b,d,c,wa),b.rb=c.buttons)}}
function Za(b,a,c){if(!b.Z&&!ua(c)){var d=b.rb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.rb=c.buttons;Va(b,c.type,c,wa)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},I)}}
function $a(b,a){document.body.style.transform="";if(0<a){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),b=(c.top+c.bottom)/2-(b-a)/2,b>a&&(b=a),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`))}}function ab(b,a,c,d){const e=b.ta(),f=b.la();b.Ua=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.$a()}):10>d&&bb(b,e,f,d+1)}
function bb(b,a,c,d){-1!==b.Ua&&clearTimeout(b.Ua);b.Ua=setTimeout(()=>ab(b,a,c,d),48)}
function Sa(b){b=b.Xc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.Ga(class extends self.Ha{constructor(b){super(b,"runtime");this.Ed=!0;this.Ua=-1;this.Xc="any";this.rd=this.sd=!1;this.Ca=null;this.Z=!1;this.zd="";this.Lc=-1;this.Na=this.ub=null;this.ac=this.$b=0;this.xd=!1;this.Id=b.ta();this.Qb=b.la();this.xb=0;b.D("canvas","update-size",d=>{var e=this.m;e.Qc||(e=e.G,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.Ed&&(e.style.display="",this.Ed=!1))});b.D("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Ia(d));b.D("runtime","get-svg-image-size",d=>Ja(d));b.D("runtime","set-target-orientation",d=>{this.Xc=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime","post-to-debugger",d=>Ka(d));b.D("runtime","go-to-script",d=>
Ka(d));b.D("runtime","before-start-ticking",()=>Ma(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ca||(this.Ca=document.createElement("div"),this.Ca.id="inspectOutline",document.body.appendChild(this.Ca));var e=this.Ca;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ca&&(this.Ca.style.display="none")});b.D("runtime","enable-device-orientation",()=>Oa(this));b.D("runtime","enable-device-motion",
()=>Pa(this));b.D("runtime","add-stylesheet",d=>Qa(d));b.D("runtime","alert",d=>this.Ac(d));b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.m.G.style.display="";this.m.re(d.duration)});b.D("runtime","export-to-video-progress",
d=>Ra(this,d));b.D("runtime","exported-to-video",d=>{window.Ve({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.Ve({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ca(e)||d.preventDefault()});const c=b.G;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",K);c.addEventListener("selectstart",
K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.rb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.Z){var d=this.ta();
var e=this.la();if(this.m.qc()){if(this.xd){if(this.Id===d&&e<this.Qb){this.xb=this.Qb-e;$a(this.Qb,this.xb);d=void 0;break a}0<this.xb&&(this.xb=0,$a(e,this.xb))}this.Id=d;this.Qb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.$a()});this.m.rc()&&(-1!==this.Ua&&clearTimeout(this.Ua),ab(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",()=>L(this));
window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Ta(this,d));window.addEventListener("webkitfullscreenerror",d=>Ta(this,d));window.addEventListener("mozfullscreenerror",d=>Ta(this,d));if(b.rc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ca(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.Hb(!0),L(this)):"exited-fullscreen"===d?(H.Hb(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Pa=new Set;this.Ub=new WeakSet;this.ua=!1}bd(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,xa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},xa);this.rb=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||Ca(a))&&k(this,"keyboard-blur",null,xa)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("dblclick",a=>Va(this,"dblclick",a,I));window.addEventListener("wheel",
a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Wa(a);M(this,"pointerdown",a)}),this.m.ia&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ub=new self.qe(()=>{M(this,"pointermove",this.Na);this.Na=null}),this.ub.vd=!0,window.addEventListener("pointerrawupdate",
a=>{this.Na&&(this.$b+=this.Na.movementX||0,this.ac+=this.Na.movementY||0);this.Na=a;a=this.ub;if(-1===a.Va){var c=Date.now(),d=c-a.Pb,e=a.Oe;d>=e&&a.vd?(a.Pb=c,a.kb=!0,a.Hc(),a.kb=!1):a.Va=self.setTimeout(a.Sd,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Wa(a);Za(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Za(this,"pointermove",a)),window.addEventListener("mouseup",a=>Za(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Wa(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Dc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.m.le()&&!this.m.qc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{$a(this.la(),navigator.virtualKeyboard.boundingRect.height)}))}ta(){return this.m.ta()}la(){return this.m.la()}Dc(){var b=[...this.Pa];this.Pa.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Ub.has(a)||this.Pa.add(a)})}aa(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Ub.delete(b);let a;try{a=b.play()}catch(c){this.Pa.add(b);return}a&&a.catch(()=>{this.Ub.has(b)||this.Pa.add(b)})}da(b){this.Pa.delete(b);this.Ub.add(b)}Eb(b){this.ua=!!b}Ac(b){alert(b.message)}});"use strict";
async function ra(b){if(b.Ne)throw Error("already initialised");b.Ne=!0;var a=b.dc.xc("dispatchworker.js");b.Kc=await b.dc.lc(a,b.eb,{name:"DispatchWorker"});a=new MessageChannel;b.Pc=a.port1;b.Kc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Wc=await ta(b)}function sa(b){return[b.Pc,b.Wc]}
async function ta(b){const a=b.Fd.length;var c=b.dc.xc("jobworker.js");c=await b.dc.lc(c,b.eb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Kc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Fd.push(c);return e.port1}
self.oe=class{constructor(b){this.dc=b;this.eb=b.ba;this.eb="preview"===b.A?this.eb+"workers/":this.eb+b.ec;this.Qe=Math.min(navigator.hardwareConcurrency||2,16);this.Kc=null;this.Fd=[];this.Wc=this.Pc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ka({ef:!0,ff:"workermain.js",Wa:["scripts/c3runtime.js"],jc:[],Zc:"",bf:"scripts/",ad:[],Td:"html5"}));"use strict";
async function cb(b,a){a=a.type;let c=!0;0===a?c=await db():1===a&&(c=await eb());k(b,"permission-result",{type:a,result:c})}async function db(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function eb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.ka.Ga(class extends self.Ha{constructor(b){super(b,"touch");n(this,"request-permission",a=>cb(this,a))}});"use strict";
async function fb(b,a){b.Sc=a.isInWorker;a=document.createElement("video");b.fc=!!a.requestVideoFrameCallback&&!b.m.qc();const c=!!self.createImageBitmap;b.vb=b.Sc||c;return{postImageBitmaps:b.vb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function gb(b,a){if(!b.Jc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>gb(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function O(b,a,c,d){b.Jc.has(a)||v(b,"playback-event",c,{type:d})}
self.ka.Ga(class extends self.je{constructor(b){super(b);this.vb=this.fc=this.Sc=this.cb=!1;this.Vb=this.Ue=0;this.Jc=new WeakSet;n(this,"init",a=>fb(this,a));w(this,"play",a=>{this.aa(a)});w(this,"pause",a=>{this.da(a);a.pause()});w(this,"set-source",(a,c)=>{a.src=c.src;a.load()});w(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});w(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});w(this,"set-looping",(a,c)=>{a.loop=c.isLooping});w(this,"set-muted",(a,c)=>{a.muted=c.isMuted});w(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>this.W.get(a)}aa(b){this.m.aa(b);this.vb&&this.fc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>gb(this,b)))}da(b){this.m.da(b);this.vb&&this.fc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}fd(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>O(this,c,b,0));c.addEventListener("canplaythrough",()=>O(this,c,b,1));c.addEventListener("ended",()=>O(this,c,b,2));c.addEventListener("error",()=>O(this,c,b,3));c.addEventListener("loadstart",()=>O(this,c,b,4));c.addEventListener("playing",()=>O(this,c,b,5));c.addEventListener("pause",()=>O(this,c,b,6));c.addEventListener("stalled",()=>O(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.aa(c);this.Vb++;u(this);return c}ld(){}hd(b){this.da(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.Vb=Math.max(this.Vb-1,0);0===this.Vb&&aa(this);this.Jc.add(b)}za(){const b={},a={sequenceNumber:this.Ue++,videoData:b},c=[],d=[];for(const [e,f]of this.W.entries()){const g={currentTime:f.currentTime,playbackRate:f.playbackRate,duration:f.duration,videoWidth:f.videoWidth,videoHeight:f.videoHeight};
if(this.vb)if(this.fc){const h=f.c3_imageBitmap;f.c3_imageBitmap=null;(g.imageBitmap=h)&&c.push(h)}else d.push(createImageBitmap(f).then(h=>{g.imageBitmap=h;c.push(h)}).catch(()=>{g.imageBitmap=null}));b[e.toString()]=g}Promise.all(d).then(()=>{this.Sc?k(this,"state",a,!1,c):l(this,"state",a)})}});"use strict";const hb=180/Math.PI;
async function ib(b,a){a.isiOSCordova&&(b.Yb=!0);b.Yc=a.timeScaleMode;b.Kd=["equalpower","HRTF","soundfield"][a.panningModel];b.wd=["linear","inverse","exponential"][a.distanceModel];b.Ld=a.refDistance;b.Jd=a.maxDistance;b.Nd=a.rolloffFactor;if(b.m.Qc)b.Yb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.yd)});else{var c={latencyHint:a.latencyHint};b.Qd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");jb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&jb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.La=b.g.createGain();b.La.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state}}
async function kb(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Gd=g;lb(b,g);try{b.na=await mb(b,c,d,e,g,f);if(q){Q(b.na,!0);var A=b.na,Z=q.innerAngle,E=q.outerAngle,yb=q.outerGain;if(A.lb){nb(A,q.x,q.y,q.angle);var La=self.Xa.se;A.F.coneInnerAngle=La(Z);A.F.coneOuterAngle=
La(E);A.F.coneOuterGain=yb}q.hasOwnProperty("uid")&&(b.na.ma=q.uid)}else Q(b.na,!1);b.na.Play(h,m,p,t)}catch(zb){console.error("[Construct] Audio: error starting playback: ",zb);return}finally{c=b.tb.get(g);if(!c)throw Error("expected pending tag");c.$c--;0===c.$c&&(c.resolve(),b.tb.delete(g))}u(b)}
async function ob(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await pb(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.Ma){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.u.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Fa=f;c.ib=g;c.Pd=h}}S(b)}async function qb(b,a){const c=a.tag;a=a.rate;await pb(b,c);for(const d of R(b,c))b=d,b.ha!==a&&(b.ha=a,b.Aa())}
async function rb(b,a){const c=a.tag;a=a.pos;await pb(b,c);for(const d of R(b,c))d.sc(a)}async function sb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await mb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function tb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.fa.indexOf(a),-1!==a&&b.fa.splice(a,1)}
async function ub(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Zd(b,...e);else if("delay"===c)e=new self.Xd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Wd(b,c.ea,...e);var f=a.bufferType;c.td=a.bufferOriginalUrl;c.ud=f}else if("flanger"===c)e=new self.$d(b,...e);else if("phaser"===c)e=new self.be(b,...e);else if("gain"===c)e=
new self.ae(b,...e);else if("tremolo"===c)e=new self.de(b,...e);else if("ringmod"===c)e=new self.ce(b,...e);else if("distortion"===c)e=new self.Yd(b,...e);else if("compressor"===c)e=new self.Vd(b,...e);else if("analyser"===c)e=new self.Ud(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ga.get(d);e||(e=[],b.ga.set(d,e));a.Dd=e.length;a.ca=d;e.push(a);vb(b,d);wb(b)}
async function xb(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.ya()&&1===c||(d.ya()||2!==c)&&d.sa();for(const e of b.ga.values())for(const f of e)f.j();b.ga.clear();b.hc=a.timeScale;b.Mc=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.ua=a.isSilent;b.m.Eb(b.ua);b.Tb=a.masterVolume;b.La.gain.value=b.Tb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>ub(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>Ab(b,e,c)));S(b)}
async function Bb(b,a){try{const c=b.g.suspend(a.time);b.Cd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.Cb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Cb(d)),b.Cd=!0);await c}catch(c){Cb(c)}}
function jb(b){b.Mb||(b.Oc=!1,window.addEventListener("pointerup",b.wa,!0),window.addEventListener("touchend",b.wa,!0),window.addEventListener("click",b.wa,!0),window.addEventListener("keydown",b.wa,!0),b.Mb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.fa)if(g.Za()===c)return await Db(g),g;if(f)return null;if(e&&(b.Yb||b.Bd)){f=0;for(let h=0,m=b.fa.length;h<m;++h)g=b.fa[h],b.fa[f]=g,g.ya()?g.j():++f;b.fa.length=f}f="audio/webm; codecs=opus"===d&&!b.Qd;e&&f&&(b.Bd=!0);a=!e||b.Yb||f?new self.ge(b,a,c,d,e,f):new self.ee(b,a,c,d,e);b.fa.push(a);await Db(a);return a}function Eb(b,a){return(a=b.ga.get(a.toLowerCase()))?a[0].R():b.xa()}
function vb(b,a){let c=b.xa();var d=b.ga.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.xa()):e.U(d[f+1].R())}}for(const f of R(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Da&&b.Uc===a&&(b.Da.disconnect(),b.Da.connect(c))}function*R(b,a){if(a)for(const c of b.L)b=c.ca,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.na&&!b.na.S()&&(yield b.na)}
function Fb(b,a,c){return c?b.m.Me(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Gb(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function mb(b,a,c,d,e,f){for(const g of b.L)if(g.Za()===c&&(g.kc()||f))return g.ca=e,g;a=await P(b,a,c,d,f);e="html5"===a.Gc?new self.fe(a.u,a,e):new self.he(a.u,a,e);b.L.push(e);return e}
function lb(b,a){let c=b.tb.get(a);if(!c){let d=null;c={$c:0,promise:new Promise(e=>d=e),resolve:d};b.tb.set(a,c)}c.$c++}function pb(b,a){a||(a=b.Gd);return(b=b.tb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ka.size)u(b);else for(const a of b.L)if(!a.H&&!a.S()){u(b);break}}function Hb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function wb(b){b.Rc||(b.Rc=!0,Promise.resolve().then(()=>Ib(b)))}
function Ib(b){const a={};for(const [c,d]of b.ga)a[c]=d.map(e=>e.Ya());k(b,"fxstate",{fxstate:a});b.Rc=!1}
async function Ab(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await mb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;a.pan?(Q(b,!0),d=b.F,e=d.pos,b.qa[0]=e[0],b.qa[1]=e[1],b.qa[2]=e[2],e=d.orient,b.pa[0]=e[0],b.pa[1]=e[1],b.pa[2]=e[2],d.setPosition(...b.qa),d.setOrientation(...b.pa),d.coneInnerAngle=d.cia,d.coneOuterAngle=
d.coa,d.coneOuterGain=d.cog,b.ma=d.uid):Q(b,!1);c.Play(m,p,q,0);a.isPlaying||c.ab();c.zc(a)}}}function Cb(b){console.error("[Audio] Offline rendering error: ",b)}
self.Xa=class extends self.Ha{constructor(b){super(b,"audio");this.La=this.g=null;this.Mb=this.Oc=!1;this.wa=()=>{if(!this.Oc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Mb&&(this.Oc=!0,window.removeEventListener("pointerup",this.wa,!0),window.removeEventListener("touchend",this.wa,!0),window.removeEventListener("click",this.wa,!0),window.removeEventListener("keydown",
this.wa,!0),this.Mb=!1)}};this.fa=[];this.L=[];this.na=null;this.Gd="";this.Hd=-1;this.tb=new Map;this.Tb=1;this.ua=!1;this.Yc=0;this.hc=1;this.Mc=0;this.Kd="HRTF";this.wd="inverse";this.Ld=600;this.Jd=1E4;this.Nd=1;this.Bd=this.Yb=!1;this.Qd=this.m.me();this.ga=new Map;this.Ka=new Set;this.Cd=this.Rc=!1;this.Uc="";this.Da=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Da&&this.Da.disconnect();this.Uc=c.toLowerCase();this.Da=this.g.createMediaStreamSource(a);this.Da.connect(Eb(this,this.Uc))};
this.Kb=null;self.C3Audio_GetOutputStream=()=>{this.Kb||(this.Kb=this.g.createMediaStreamDestination(),this.La.connect(this.Kb));return this.Kb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>ib(this,a)],["play",a=>kb(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.sa()}],["stop-all",()=>{for(const a of this.L)a.sa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.ab():d.Db();S(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of R(this,
c))T(d,a)}],["fade-volume",a=>ob(this,a)],["set-master-volume",a=>{this.Tb=a.vol;this.La.gain.value=this.Tb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Jb(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.m.Eb(this.ua);for(const c of this.L)c.Ib()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.tc(a)}],["set-playback-rate",a=>qb(this,a)],["seek",a=>rb(this,a)],["preload",a=>sb(this,a)],["unload",a=>tb(this,a)],["unload-all",()=>{for(const a of this.fa)a.j();
this.fa.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.uc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>ub(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ga.get(a.tag);!a||0>c||c>=a.length||(a[c].$(d,e,f,g),wb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.ga.get(a);if(c&&c.length){for(const d of c)d.j();this.ga.delete(a);vb(this,a)}}],["tick",a=>{this.hc=a.timeScale;
this.Mc=a.gameTime;this.Hd=a.tickCount;if(0!==this.Yc)for(var c of this.L)c.Aa();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ma===a&&nb(e,d.x,d.y,d.angle)}}],["load-state",a=>xb(this,a)],["offline-render-audio",a=>Bb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}Y(){return this.g}xa(){return this.La}Bb(){return this.ua}aa(b){this.m.aa(b)}da(b){this.m.da(b)}za(){for(var b of this.Ka)b.za();b=this.g.currentTime;
for(var a of this.L)a.za(b);a=this.L.filter(c=>!c.H&&!c.S()).map(c=>c.Ya());k(this,"state",{tickCount:this.Hd,audioInstances:a,analysers:[...this.Ka].map(c=>({tag:c.ca,index:c.Dd,peak:c.Qa,rms:c.Md,binCount:c.o.frequencyBinCount,freqBins:c.Ad}))});0===a.length&&0===this.Ka.size&&aa(this)}static se(b){return b*hb}static gd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static pe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.ka.Ga(self.Xa);"use strict";
function Db(b){b.Rb||(b.Rb=b.yc());return b.Rb}self.cd=class{constructor(b,a,c,d,e){this.u=b;this.Se=a;this.Ea=c;this.T=d;this.Pe=e;this.Gc="";this.Rb=null}j(){this.Rb=this.u=null}yc(){}Y(){return this.u.Y()}nc(){return this.Se}Za(){return this.Ea}mc(){return this.T}ya(){return this.Pe}ja(){}};"use strict";
self.ee=class extends self.cd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Gc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.nb=this.ob=null;this.K.addEventListener("canplaythrough",()=>!0);this.sb=this.Y().createGain();this.qb=null;this.K.addEventListener("canplay",()=>{this.ob&&(this.ob(),this.nb=this.ob=null);!this.qb&&this.K&&(this.qb=this.Y().createMediaElementSource(this.K),this.qb.connect(this.sb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ea}' error: `,f);this.nb&&(this.nb(f),this.nb=this.ob=null)})}j(){Gb(this.u,this);this.sb.disconnect();this.sb=null;this.qb.disconnect();this.qb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}yc(){return new Promise((b,a)=>{this.ob=b;this.nb=a;this.K.src=this.Ea})}P(){return this.K}ja(){return this.K.duration}};"use strict";
async function Kb(b){if(b.Ba)return b.Ba;var a=b.u.m;if("cordova"===a.A&&a.jd(b.Ea)&&a.Ob)b.Ba=await a.Ab(b.Ea);else{a=await fetch(b.Ea);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ba=await a.arrayBuffer()}}async function Lb(b){if(b.ea)return b.ea;b.ea=await Fb(b.u,b.Ba,b.Re);b.Ba=null}
self.ge=class extends self.cd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Gc="webaudio";this.ea=this.Ba=null;this.Re=!!f}j(){Gb(this.u,this);this.ea=this.Ba=null;super.j()}async yc(){try{await Kb(this),await Lb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ea}': `,b)}}ja(){return this.ea?this.ea.duration:0}};"use strict";let Mb=0;
function Q(b,a){a=!!a;b.lb!==a&&(b.lb=a,b.lb?(b.F||(b.F=b.Y().createPanner(),b.F.panningModel=b.u.Kd,b.F.distanceModel=b.u.wd,b.F.refDistance=b.u.Ld,b.F.maxDistance=b.u.Jd,b.F.rolloffFactor=b.u.Nd),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.xa())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.xa())))}function T(b,a){b.Fa=a;b.N.gain.cancelScheduledValues(0);b.ib=-1;b.N.gain.value=b.oc()}function Jb(b,a){a=!!a;b.Ma!==a&&(b.Ma=a,b.Ib())}
function nb(b,a,c,d){b.lb&&(b.qa[0]=a,b.qa[1]=c,b.qa[2]=0,b.pa[0]=Math.cos(d),b.pa[1]=Math.sin(d),b.pa[2]=0,b.F.setPosition(...b.qa),b.F.setOrientation(...b.pa))}function U(b){return b.Tc?b.u.Mc:performance.now()/1E3}
self.dd=class{constructor(b,a,c){this.u=b;this.M=a;this.ca=c;this.Jb=Mb++;this.N=this.Y().createGain();this.N.connect(this.xa());this.F=null;this.lb=!1;this.qa=[0,0,0];this.pa=[0,0,0];this.H=!0;this.X=this.ra=this.I=!1;this.Fa=1;this.Ma=!1;this.ha=1;b=this.u.Yc;this.Tc=1===b&&!this.ya()||2===b;this.ib=this.ma=-1;this.Pd=!1}j(){this.M=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}Y(){return this.u.Y()}xa(){return Eb(this.u,this.ca)}nc(){return this.M.nc()}Za(){return this.M.Za()}mc(){return this.M.mc()}ya(){return this.M.ya()}S(){}kc(){}IsPlaying(){return!this.H&&
!this.I&&!this.S()}Ia(){}ja(){return this.M.ja()}Play(){}sa(){}ab(){}Db(){}za(b){-1!==this.ib&&b>=this.ib&&(this.ib=-1,this.Pd&&this.sa(),Hb(this.u,"fade-ended",this.ca,this.Jb))}oc(){const b=this.Fa;return isFinite(b)?b:0}Bb(){return this.u.Bb()}Ib(){}tc(){}Aa(){}sc(){}uc(){}pc(){}Ya(){var b=this.Jb,a=this.ca,c=this.ja(),d=this.Fa,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.qa,orient:this.pa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ma}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ia(),playbackRate:this.ha,uid:this.ma,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.ya(),isLooping:this.X,isMuted:this.Ma,resumePosition:this.pc(),pan:f}}zc(b){var a=b.playbackRate;this.ha!==a&&(this.ha=a,this.Aa());Jb(this,b.isMuted)}};"use strict";
self.fe=class extends self.dd{constructor(b,a,c){super(b,a,c);this.M.sb.connect(this.N);this.M.onended=()=>this.Bc()}j(){this.sa();this.M.sb.disconnect();super.j()}P(){return this.M.P()}Bc(){this.H=!0;this.ma=-1;Hb(this.u,"ended",this.ca,this.Jb)}S(){return this.P().ended}kc(){return this.H?!0:this.S()}Ia(){let b=this.P().currentTime;this.X||(b=Math.min(b,this.ja()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.Za()}' to position '${c}': `,e)}this.u.aa(d);this.I=this.H=!1;this.X=b;this.ha=1}sa(){const b=this.P();b.paused||b.pause();this.u.da(b);this.H=!0;this.I=!1;this.ma=-1}ab(){if(!(this.I||this.H||this.S())){var b=this.P();b.paused||b.pause();this.u.da(b);this.I=!0}}Db(){!this.I||this.H||this.S()||(this.u.aa(this.P()),this.I=!1)}Ib(){this.P().muted=this.Ma||this.Bb()}tc(b){b=!!b;this.X!==b&&(this.X=
b,this.P().loop=b)}Aa(){let b=this.ha;this.Tc&&(b*=this.u.hc);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}sc(b){if(!this.H&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.Ia()}uc(b){b?this.IsPlaying()?(this.P().pause(),this.ra=!0):this.ra=!1:this.ra&&(this.u.aa(this.P()),this.ra=!1)}};"use strict";function V(b){b.s&&b.s.disconnect();b.s=null;b.bb=null}
self.he=class extends self.dd{constructor(b,a,c){super(b,a,c);this.s=null;this.Wb=d=>this.Bc(d);this.Nc=!0;this.bb=null;this.O=this.Xb=this.Zb=0;this.Vc=1}j(){this.sa();V(this);this.Wb=null;super.j()}Bc(b){this.I||this.ra||b.target!==this.bb||(this.H=this.Nc=!0,this.ma=-1,V(this),Hb(this.u,"ended",this.ca,this.Jb))}S(){return!this.H&&this.s&&this.s.loop||this.I?!1:this.Nc}kc(){return!this.s||this.H?!0:this.S()}Ia(){let b;b=this.I?this.O:this.Xb+(U(this)-this.Zb)*this.ha;this.X||(b=Math.min(b,this.ja()));
return b}Play(b,a,c,d){this.Vc=1;T(this,a);V(this);this.s=this.Y().createBufferSource();this.s.buffer=this.M.ea;this.s.connect(this.N);this.bb=this.s;this.s.onended=this.Wb;this.s.loop=b;this.s.start(d,c);this.I=this.H=this.Nc=!1;this.X=b;this.ha=1;this.Zb=U(this);this.Xb=c}sa(){if(this.s)try{this.s.stop(0)}catch(b){}this.H=!0;this.I=!1;this.ma=-1}ab(){this.I||this.H||this.S()||(this.O=this.Ia(),this.X&&(this.O%=this.ja()),this.I=!0,this.s.stop(0))}Db(){!this.I||this.H||this.S()||(V(this),this.s=
this.Y().createBufferSource(),this.s.buffer=this.M.ea,this.s.connect(this.N),this.bb=this.s,this.s.onended=this.Wb,this.s.loop=this.X,T(this,this.Fa),this.Aa(),this.s.start(0,this.O),this.Zb=U(this),this.Xb=this.O,this.I=!1)}oc(){return super.oc()*this.Vc}Ib(){this.Vc=this.Ma||this.Bb()?0:1;T(this,this.Fa)}tc(b){b=!!b;this.X!==b&&(this.X=b,this.s&&(this.s.loop=b))}Aa(){let b=this.ha;this.Tc&&(b*=this.u.hc);this.s&&(this.s.playbackRate.value=b)}sc(b){this.H||this.S()||(this.I?this.O=b:(this.ab(),this.O=
b,this.Db()))}pc(){return this.O}uc(b){b?this.IsPlaying()?(this.ra=!0,this.O=this.Ia(),this.X&&(this.O%=this.ja()),this.s.stop(0)):this.ra=!1:this.ra&&(V(this),this.s=this.Y().createBufferSource(),this.s.buffer=this.M.ea,this.s.connect(this.N),this.bb=this.s,this.s.onended=this.Wb,this.s.loop=this.X,T(this,this.Fa),this.Aa(),this.s.start(0,this.O),this.Zb=U(this),this.Xb=this.O,this.ra=!1)}zc(b){super.zc(b);this.O=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.Y();this.Dd=-1;this.T=this.ca="";this.l=null}j(){this.g=null}R(){}U(){}Ya(){return{type:this.T,tag:this.ca,params:this.l}}}
self.Zd=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.C=this.g.createBiquadFilter();this.C.type=a;this.C.frequency.value=c;this.C.detune.value=d;this.C.Q.value=e;this.C.gain.vlaue=f;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i)}j(){this.v.disconnect();this.C.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;X(this,this.C.frequency,a,c,d);break;case 2:this.l[2]=a;X(this,this.C.detune,a,c,d);break;case 3:this.l[3]=a;X(this,this.C.Q,a,c,d);break;case 4:this.l[4]=a,X(this,this.C.gain,a,c,d)}}};
self.Xd=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.pb=W(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.hb=W(this);this.hb.gain.value=c;this.v.connect(this.pb);this.v.connect(this.h);this.pb.connect(this.i);this.pb.connect(this.V);this.V.connect(this.hb);this.hb.connect(this.pb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.pb.disconnect();
this.V.disconnect();this.hb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}$(b,a,c,d){const e=self.Xa.gd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);X(this,this.hb.gain,e(a),c,d);break;case 5:this.l[0]=a,X(this,this.V.delayTime,a,c,d)}}};
self.Wd=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.ud=this.td="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.gb=this.g.createConvolver();this.gb.normalize=c;this.gb.buffer=a;this.v.connect(this.gb);this.v.connect(this.h);this.gb.connect(this.i)}j(){this.v.disconnect();this.gb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}$(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}Ya(){const b=super.Ya();b.bufferOriginalUrl=this.td;b.bufferUrl="";b.bufferType=this.ud;return b}};
self.$d=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.jb=W(this);this.jb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.B=this.g.createOscillator();this.B.frequency.value=d;this.J=W(this);this.J.gain.value=c;this.v.connect(this.V);this.v.connect(this.h);this.V.connect(this.i);this.V.connect(this.jb);this.jb.connect(this.V);this.B.connect(this.J);
this.J.connect(this.V.delayTime);this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.V.disconnect();this.B.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.jb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;X(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;X(this,this.B.frequency,a,c,d);break;case 8:this.l[3]=a/100,X(this,this.jb.gain,a/100,c,d)}}};
self.be=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.C=this.g.createBiquadFilter();this.C.type="allpass";this.C.frequency.value=a;this.C.detune.value=c;this.C.Q.value=d;this.B=this.g.createOscillator();this.B.frequency.value=f;this.J=W(this);this.J.gain.value=e;this.v.connect(this.C);this.v.connect(this.h);this.C.connect(this.i);this.B.connect(this.J);this.J.connect(this.C.frequency);
this.B.start(0)}j(){this.B.stop(0);this.v.disconnect();this.C.disconnect();this.B.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;X(this,this.C.frequency,a,c,d);break;case 2:this.l[1]=a;X(this,this.C.detune,a,c,d);
break;case 3:this.l[2]=a;X(this,this.C.Q,a,c,d);break;case 6:this.l[3]=a;X(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,X(this,this.B.frequency,a,c,d)}}};self.ae=class extends Y{constructor(b,a){super(b);this.T="gain";this.l=[a];this.o=W(this);this.o.gain.value=a}j(){this.o.disconnect();super.j()}U(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}$(b,a,c,d){const e=self.Xa.gd;switch(b){case 4:this.l[0]=e(a),X(this,this.o.gain,e(a),c,d)}}};
self.de=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.o=W(this);this.o.gain.value=1-c/2;this.B=this.g.createOscillator();this.B.frequency.value=a;this.J=W(this);this.J.gain.value=c/2;this.B.connect(this.J);this.J.connect(this.o.gain);this.B.start(0)}j(){this.B.stop(0);this.B.disconnect();this.J.disconnect();this.o.disconnect();super.j()}U(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;X(this,this.o.gain,1-a/2,c,d);X(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.ce=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.wb=W(this);this.wb.gain.value=0;this.B=this.g.createOscillator();this.B.frequency.value=a;this.B.connect(this.wb.gain);this.B.start(0);this.v.connect(this.wb);this.v.connect(this.h);this.wb.connect(this.i)}j(){this.B.stop(0);this.B.disconnect();this.wb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,X(this,this.B.frequency,a,c,d)}}};
self.Yd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.v=W(this);this.cc=W(this);this.bc=W(this);b=d;.01>b&&(b=.01);this.cc.gain.value=b;this.bc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.ic=this.g.createWaveShaper();this.Ic=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ic[32768+e]=f,this.Ic[32768-
e-1]=-f;this.ic.curve=this.Ic;this.v.connect(this.cc);this.v.connect(this.h);this.cc.connect(this.ic);this.ic.connect(this.bc);this.bc.connect(this.i)}j(){this.v.disconnect();this.cc.disconnect();this.ic.disconnect();this.bc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Vd=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.o=this.g.createDynamicsCompressor();this.o.threshold.value=a;this.o.knee.value=c;this.o.ratio.value=d;this.o.attack.value=e;this.o.release.value=f}j(){this.o.disconnect();super.j()}U(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}$(){}};
self.Ud=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.o=this.g.createAnalyser();this.o.fftSize=a;this.o.smoothingTimeConstant=c;this.Ad=new Float32Array(this.o.frequencyBinCount);this.Od=new Uint8Array(a);this.Md=this.Qa=0;b=this.u;b.Ka.add(this);S(b)}j(){this.u.Ka.delete(this);this.o.disconnect();super.j()}za(){this.o.getFloatFrequencyData(this.Ad);this.o.getByteTimeDomainData(this.Od);const b=this.o.fftSize;let a=this.Qa=0;for(var c=0;c<b;++c){let d=(this.Od[c]-
128)/128;0>d&&(d=-d);this.Qa<d&&(this.Qa=d);a+=d*d}c=self.Xa.pe;this.Qa=c(this.Qa);this.Md=c(Math.sqrt(a/b))}U(b){this.o.disconnect();this.o.connect(b)}R(){return this.o}$(){}};"use strict";
self.ka.Ga(class extends self.Ha{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.m.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function Nb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>k(b,"sw-message",a.data))}
function Ob(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.ka.Ga(class extends self.Ha{constructor(b){super(b,"browser");this.A="";r(this,[["get-initial-state",a=>{this.A=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
Nb(this)],["alert",a=>this.Ac(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Cc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ob(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||"windows-webview2"===a?window.open(c,"_blank"):this.kf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if("windows-webview2"===this.A||"macos-wkwebview"===this.A)self.ka.Hb(!0),this.m.Fc({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===
a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(c):a.mozRequestFullScreen?a.mozRequestFullScreen(c):a.msRequestFullscreen?a.msRequestFullscreen(c):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.A||"macos-wkwebview"===this.A?(self.ka.Hb(!1),this.m.Fc({type:"set-fullscreen",
fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{k(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{k(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{k(this,"hashchange",
{location:location.toString()})});document.addEventListener("backbutton",()=>{k(this,"backbutton")})}Ac(b){alert(b.message)}Cc(b){b=b.isFocus;if("nwjs"===this.A){const a="nwjs"===this.A?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
